require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
=begin
describe UtilizedBitcoinWalletsController do

  # This should return the minimal set of attributes required to create a valid
  # UtilizedBitcoinWallet. As you add validations to UtilizedBitcoinWallet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "wallet_address" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UtilizedBitcoinWalletsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all utilized_bitcoin_wallets as @utilized_bitcoin_wallets" do
      utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:utilized_bitcoin_wallets).should eq([utilized_bitcoin_wallet])
    end
  end

  describe "GET show" do
    it "assigns the requested utilized_bitcoin_wallet as @utilized_bitcoin_wallet" do
      utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
      get :show, {:id => utilized_bitcoin_wallet.to_param}, valid_session
      assigns(:utilized_bitcoin_wallet).should eq(utilized_bitcoin_wallet)
    end
  end

  describe "GET new" do
    it "assigns a new utilized_bitcoin_wallet as @utilized_bitcoin_wallet" do
      get :new, {}, valid_session
      assigns(:utilized_bitcoin_wallet).should be_a_new(UtilizedBitcoinWallet)
    end
  end

  describe "GET edit" do
    it "assigns the requested utilized_bitcoin_wallet as @utilized_bitcoin_wallet" do
      utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
      get :edit, {:id => utilized_bitcoin_wallet.to_param}, valid_session
      assigns(:utilized_bitcoin_wallet).should eq(utilized_bitcoin_wallet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UtilizedBitcoinWallet" do
        expect {
          post :create, {:utilized_bitcoin_wallet => valid_attributes}, valid_session
        }.to change(UtilizedBitcoinWallet, :count).by(1)
      end

      it "assigns a newly created utilized_bitcoin_wallet as @utilized_bitcoin_wallet" do
        post :create, {:utilized_bitcoin_wallet => valid_attributes}, valid_session
        assigns(:utilized_bitcoin_wallet).should be_a(UtilizedBitcoinWallet)
        assigns(:utilized_bitcoin_wallet).should be_persisted
      end

      it "redirects to the created utilized_bitcoin_wallet" do
        post :create, {:utilized_bitcoin_wallet => valid_attributes}, valid_session
        response.should redirect_to(UtilizedBitcoinWallet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved utilized_bitcoin_wallet as @utilized_bitcoin_wallet" do
        # Trigger the behavior that occurs when invalid params are submitted
        UtilizedBitcoinWallet.any_instance.stub(:save).and_return(false)
        post :create, {:utilized_bitcoin_wallet => { "wallet_address" => "invalid value" }}, valid_session
        assigns(:utilized_bitcoin_wallet).should be_a_new(UtilizedBitcoinWallet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UtilizedBitcoinWallet.any_instance.stub(:save).and_return(false)
        post :create, {:utilized_bitcoin_wallet => { "wallet_address" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested utilized_bitcoin_wallet" do
        utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
        # Assuming there are no other utilized_bitcoin_wallets in the database, this
        # specifies that the UtilizedBitcoinWallet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UtilizedBitcoinWallet.any_instance.should_receive(:update_attributes).with({ "wallet_address" => "MyText" })
        put :update, {:id => utilized_bitcoin_wallet.to_param, :utilized_bitcoin_wallet => { "wallet_address" => "MyText" }}, valid_session
      end

      it "assigns the requested utilized_bitcoin_wallet as @utilized_bitcoin_wallet" do
        utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
        put :update, {:id => utilized_bitcoin_wallet.to_param, :utilized_bitcoin_wallet => valid_attributes}, valid_session
        assigns(:utilized_bitcoin_wallet).should eq(utilized_bitcoin_wallet)
      end

      it "redirects to the utilized_bitcoin_wallet" do
        utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
        put :update, {:id => utilized_bitcoin_wallet.to_param, :utilized_bitcoin_wallet => valid_attributes}, valid_session
        response.should redirect_to(utilized_bitcoin_wallet)
      end
    end

    describe "with invalid params" do
      it "assigns the utilized_bitcoin_wallet as @utilized_bitcoin_wallet" do
        utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UtilizedBitcoinWallet.any_instance.stub(:save).and_return(false)
        put :update, {:id => utilized_bitcoin_wallet.to_param, :utilized_bitcoin_wallet => { "wallet_address" => "invalid value" }}, valid_session
        assigns(:utilized_bitcoin_wallet).should eq(utilized_bitcoin_wallet)
      end

      it "re-renders the 'edit' template" do
        utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UtilizedBitcoinWallet.any_instance.stub(:save).and_return(false)
        put :update, {:id => utilized_bitcoin_wallet.to_param, :utilized_bitcoin_wallet => { "wallet_address" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested utilized_bitcoin_wallet" do
      utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
      expect {
        delete :destroy, {:id => utilized_bitcoin_wallet.to_param}, valid_session
      }.to change(UtilizedBitcoinWallet, :count).by(-1)
    end

    it "redirects to the utilized_bitcoin_wallets list" do
      utilized_bitcoin_wallet = UtilizedBitcoinWallet.create! valid_attributes
      delete :destroy, {:id => utilized_bitcoin_wallet.to_param}, valid_session
      response.should redirect_to(utilized_bitcoin_wallets_url)
    end
  end

end
=end